### ISSUE TITLE
InfluxDB Enterprise Features

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/influxdb#51]
## Use Case
We have a client who is using InfluxDB Enterprise and has created types and providers for InfluxDB Enterprise. The Client is looking for an upstream module to donate the features to. 

## Describe the Solution You Would Like
Integrate the InfluxDB Enterprise Features

## Additional Context
Are you open to take these features to extend this module?

**Comment by MartyEwings** [comment]
@SimonHoenscheid yep so long as it does no interfere with the primary use case of this module for us (which is to feed the ops dashboard) we are open to anything that makes this module better and more useful

**Comment by SimonHoenscheid** [comment]
@MartyEwings Thanks for the quick response. I will prepare a Pull Request.
