### ISSUE TITLE
toml_rb gem fact is hardcoded to 2.1.1

### ISSUE THREAD

**Issue by zoojar** [puppetlabs/influxdb#54]
## Describe the Bug
toml_rb gem fact is hardcoded to 2.1.1: https://github.com/puppetlabs/influxdb/blob/80f406eb221501aa50364c5b9d875624a4f4e91f/lib/facter/toml_rb_gem.rb#L5

## Expected Behavior
A different version of the gem should be supported or configured

## Steps to Reproduce
facter -p toml_rb_gem

## Environment
Centos 8

**Comment by m0dular** [comment]
Closing as this was removed in #58
